function [ spots,rfp, gfp, intensity, mintensity ] = MasktoSpotsSignal( mask,filename, schn_path, exp_date, index, colorchannel)
%MASKTOSPOTSSIGNAL quantify spots signal based on cell masks
%   2020-10
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   OUTPUT
%   spots: the intensity of spots
%   rfp: total spots intensity per cell
%   gfp: fluorescence for segmentation channel
%   intensity: total fluorescence of spot channel for each cell
%   mintensity: mean intensity of the spot channel for each cell
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   INPUT
%   mask, filename, schn_path and exp_date are generated by running the
%   Schnitzcells program. sch_path is the path to the sample folder under 
%   Schnitzcells.Filename is the path and filename of the source images.
%   index is the first two digits in the filename, ranging from 1 to n.
%   colorchannel is the last two digits of the file name: 3 for RFP channel 
%   and 2 for CFP channel.
%   For example, 'Multichannel-0002.tif' is the 1st image in CFP channel
%   and 'Multichannel-0103.tif' is the 2nd image in RFP channel.

%% read all images
if colorchannel == 3
    %read the RFP channel 
    imgr = imread([filename(1:length(filename)-6) num2str(3,'%02d') '.tif']);
    color_thres = 60;
end

if colorchannel == 2
    %read the CFP channel
    imgr = imread([filename(1:length(filename)-6) num2str(2,'%02d') '.tif']);
    imgr = imresize(imgr,2);
    color_thres = 400;
end

s = size(imgr);
% import yfp/gfp channel/mask
imgr2 = imread([filename(1:length(filename)-6) num2str(1,'%02d') '.tif']);
imgr2 = imresize(imgr2,2);

%% calculate drift of images
mask2 = mask{index};
mask2(1:8,:) = 0;
mask2(:,1:8) = 0;
mask2(s(1)-8:s(1),:) = 0;
mask2(:,s(2)-8:s(2)) = 0;
for i = 1:16
    for j = 1:16
        inten(i,j) = sum(sum(imgr(find(mask2>0)+(i-8)*s(1)+j-8)));
    end
end
minten = max(inten(:));
[rindex, cindex] = find(inten == minten);
drift = (rindex-8)*s(1)+cindex-8;

%% expand mask
for i = 1:max2(mask{index})
    maski = delout(find(mask{index}==i)+drift, s(1)*s(2));
    maski(maski==0) = [];
    for j = 1:0
        additional = [maski-s(1),maski+s(1),maski-1,maski+1];
        additional = reshape(additional,4*length(maski),1);
        additional(additional<=0) = [];
        additional(additional>=s(1)*s(2)) = [];
        additional = unique(additional);
        additional_pos = additional-drift;
        additional_pos(additional_pos<=0) = [];
        additional_pos(additional_pos>s(1)*s(2)) = [];
        additional(find(mask{index}(additional_pos)>0)) = [];
        additional = setdiff(additional,maski);
        if sum(imgr(additional)>background(i)) <2
            break;
        end
        add_element = ones(size(additional));
        add_element = find(add_element == 1);
        maski = [maski; additional(add_element)];
        imgr(additional(add_element)) = minus(imgr(additional(add_element)),background(i));
    end
    mask_after{i} = maski;
end

%% calculate statistics
% get gfp statistics
for i = 1:max2(mask{index})
    gfp(i) = prctile(imgr2(find(mask{index}==i)),50);
end
% get rfp/cfp statistics
background = zeros(max2(mask{index}),1);
for i = 1:max2(mask{index})
    maski = delout(find(mask{index}==i)+drift, s(1)*s(2));
    maski(maski==0) = [];
    background(i) = prctile(imgr(maski),60);
    intensity(i) = sum(sum(imgr(maski)));
    mintensity(i) = prctile(imgr(maski),50);
end
%get spots intensity
rfp =  zeros(max2(mask{index}),1);
img_spots = zeros(size(imgr));
img_spots_mask = zeros(size(imgr));
spots = [];
s = size(imgr);
for i = 1:max2(mask{index})
    cella = zeros(size(imgr));
    maski = mask_after{i};
    cella(maski) = imgr(maski);
    PSF = fspecial('gaussian',5,1);
    Filtered = imfilter(cella,PSF,'symmetric','conv');
    Filtered = cella;
    imgr(maski) =  Filtered(maski);
    if max2(imgr(maski)) == 0
        continue;
    end
    box_size = 11;
    [i_map, j_map] = meshgrid(1:s(2),1:s(1));
    all_maxima = imregionalmax(Filtered, 8);
    maxima_i = find(all_maxima==1);
    maxima_i = remove_spot_boundary(maxima_i, maski, s);
    
    s = size(Filtered);
    for j = length(maxima_i):-1:1
        neighbor_index = [maxima_i(j)+3,maxima_i(j)-3,maxima_i(j)+3*s(1),maxima_i(j)-3*s(1)];
        neighbor_index(neighbor_index<=0) = [];
        neighbor_index(neighbor_index>=s(1)*s(2)) = [];
        neighbor = Filtered(neighbor_index);
        if sum(neighbor > Filtered(maxima_i(j))-color_thres) >1
            maxima_i(j) = [];
        end
    end
    
    for j = 1:length(maxima_i)
        pos(1)= mod(maxima_i(j)-1,s(1)) + 1;
        pos(2)= floor(maxima_i(j)/s(1));
        if  pos(1) > floor(box_size/2) && pos(2) > floor(box_size/2) &&...
                pos(1) < s(1) - floor(box_size/2) && pos(2) < s(2) - floor(box_size/2)
            Pixels_to_analyze = zeros(size(imgr));
            Pixels_to_analyze(pos(1)-floor(box_size/2):pos(1)+floor(box_size/2),pos(2)-floor(box_size/2):pos(2)+floor(box_size/2)) = 1;
            Pixels_to_analyze= find(Pixels_to_analyze==1);
            Pixels_to_analyze = intersect(Pixels_to_analyze,maski);
            if max2(img_spots_mask(Pixels_to_analyze)==i) == 0
                X1 = i_map(Pixels_to_analyze);
                X2 = j_map(Pixels_to_analyze);
                Y = imgr(Pixels_to_analyze);
                spot_height = double(Filtered(maxima_i(j)));
                p0 = [spot_height,pos(1),pos(2),1,1,0,0];
                lb = [double(Filtered(maxima_i(j)))-median(Filtered(maski))-100,pos(1)-5,pos(2)-5,0.1,0.1,0,median(Filtered(maski))];
                ub = [double(Filtered(maxima_i(j)))-median(Filtered(maski))-50,pos(1)+5,pos(2)+5,10,10,0.05,median(Filtered(maski))+30];
                [p, Y_pred, resnorm] = fitGuassian(X1, X2, Y, p0, lb, ub, pos);
                if p>0
                    spots = [spots;cat(2,p,resnorm)];
                    rfp(i) = rfp(i) + p(1);
                    img_spots(Pixels_to_analyze) = Y_pred;
                    img_spots_mask(Pixels_to_analyze) = i;
                end
            end
        end
    end
end

%% output the images and the identified spots
eval(['mkdir ''',[schn_path exp_date '\TestSchnitz-01\'],''' ','spotsc'])
write_name = [schn_path...
    exp_date '\TestSchnitz-01\spotsc\TestSchnitz-01-t-' num2str(index,'%03d') '.tif'];
imwrite(imgr,write_name);

write_name = [schn_path...
    exp_date '\TestSchnitz-01\spotsc\TestSchnitz-01-t-spots' num2str(index,'%03d') '.tif'];
imwrite(uint16(img_spots),write_name);

end

%% remove outlier of the drift
% input arg: index is for mask of cell i, s is the size of the image.
function index = delout(index, s)
index(index<0) = [];
index(index > s) = [];
end

%% fit guassian distribution
function [p, Y_pred, resnorm] = fitGuassian(X1, X2, Y, p0, lb, ub, pos)
gau2_gen = @(n) ['p(' num2str(1+6*(n-1)) ').*', ... %%% 2D single-gaussian model function text generator
                 'exp(', ...                      %%% exp(-( a(x-x0)^2 + b(y-y0)^2 + 2c(x-x0)(y-y0) ))
                 '-(', ...
                 '(p(' num2str(4+6*(n-1)) ')).*(x(:,1)-p(' num2str(2+6*(n-1)) ')).^2+', ...
                 '(p(' num2str(5+6*(n-1)) ')).*(x(:,2)-p(' num2str(3+6*(n-1)) ')).^2+', ...
               '2*(p(' num2str(6+6*(n-1)) ')).*(x(:,1)-p(' num2str(2+6*(n-1)) ')).*(x(:,2)-p(' num2str(3+6*(n-1)) '))', ...
                 '))','+p(' num2str(7+6*(n-1)) ')'];  
eval(['f = @(p,x)' gau2_gen(1) ';']);
options = optimset('Display','off');
[p, resnorm, ~, exitflag] = lsqcurvefit(f, p0, double([X2 X1]), double(Y), lb, ub,options);
a = p(4);
b = p(5);
c = p(6);
if a*b - c^2 < 0 || c > 0.1
    Y_pred = 0;
    p = zeros(1,8);;
else    
    spot_intensity = p(1)*pi/sqrt(a.*b-c.^2);
    Y_pred = f(p,[X2 X1])- p(7);
    p = [spot_intensity p];
end
end


%% remove maxima near the boundary
function maxima_i = remove_spot_boundary(maxima_i, maski, s)
     t = [];
     d = 1;
     for i = 1:length(maxima_i)
         t(i) = length(intersect([maxima_i(i) + d, maxima_i(i) - d, maxima_i(i) + d*s(1), maxima_i(i) - d*s(1)],maski));
     end
     maxima_i(find(t<4)) = [];
end
